import React from 'react';

function PrivacyPolicyPage() {
  return (
    <div className="page-content">
      <h1>Privacy Policy for ladevzo Apps</h1>
      <p>Last updated: May 28, 2025</p>
      
      <p>This Privacy Policy describes how ladevzo ("we", "us", or "our") collects, uses, and discloses your personal information when you use our various applications and services (collectively, "the Apps").</p>
      
      <h2>Information We Collect</h2>
      <p>When you use any of our Apps, we may collect the following information:</p>
      <ul>
        <li><strong>Google Profile Information:</strong> We use Google Sign-In to authenticate your identity across our Apps. Through this process, we may access your basic Google profile information, such as your name and email address. This information is used solely to authenticate you and personalize your experience within our Apps.</li>
        <li><strong>Google Photos Media Metadata:</strong> For Apps that integrate with Google Photos (such as <strong>EXIF Viewer</strong> or <strong>Slideshow</strong> apps), when you use the Google Photos Picker API or the Google Photos Library API, you grant us permission to read metadata (such as filename, dimensions, creation time, camera model, and other EXIF-like data) and temporarily access the content (image/video bytes) of the photos and videos you explicitly select or that are created by our apps.</li>
        <li><strong>App-Specific Data:</strong> Depending on the specific App you are using, we may collect information relevant to that App's functionality. For example, in <strong>EXIF Viewer</strong>, this includes the metadata displayed from your selected media. For a <strong>Slideshow</strong> app, this might involve preferences, settings, or the order of media you've chosen.</li>
      </ul>

      <h2>How We Use Your Information</h2>
      <p>The information we collect is used exclusively for the following purposes:</p>
      <ul>
        <li><strong>Authentication:</strong> To sign you in to our Apps and identify you as a user.</li>
        <li><strong>Providing App Functionality:</strong> To enable the features of each App you use. For instance, in <strong>EXIF Viewer</strong>, this means displaying the photos and videos you select from your Google Photos library, along with their metadata. For a <strong>Slideshow</strong> app, it means enabling content creation, viewing, or organization features.</li>
        <li><strong>Personalization:</strong> To tailor your experience within our Apps.</li>
      </ul>

      <h2>How We Share Your Information</h2>
      <p>ladevzo does not store your photos, videos, or any of their content persistently on our servers. We do not share any of your personal information (including your Google profile information or photo/video metadata) with any third parties.</p>
      <p>Access to your Google Photos content is direct from your browser or device to Google's servers, proxied only temporarily through our secure serverless functions (where applicable) to enable display or processing within the Apps, and is always initiated by your explicit selection or action.</p>

      <h2>Data Retention</h2>
      <p>We do not persistently store your photos, videos, or their content. Your Google Access Token is used temporarily during your session and is not persistently stored by our Apps. Session data related to your media selection or temporary app functionality is also temporary and expires after a short period (e.g., 60 minutes). Any data generated by our apps (like an album ID or simple text enrichment) that needs to persist for the app's functionality is stored securely, but never your actual media content.</p>

      <h2>Security of Your Information</h2>
      <p>We use industry-standard security measures to protect the information we handle. Access to your Google Photos is managed through secure Google OAuth 2.0 protocols.</p>

      <h2>Your Choices</h2>
      <p>You can revoke any App's access to your Google Photos or other Google services at any time through your Google Account settings (Google Account Security Settings).</p>

      <h2>Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

      <h2>Limited Use of User Data</h2>
      <p>The use of raw or derived user data received from Google Photos APIs will adhere to the Google API Services User Data Policy, including the Photos API User Data and Developer Policy Limited use of user data requirements. Specifically, ladevzo apps do not use user data obtained through Google Photos APIs to create, train, or improve foundational machine learning or artificial intelligence models. Any AI/ML functionalities within our applications are either client-side, do not involve persistent user data, or are strictly personalized to the individual user for the appropriate use case or user-facing feature and are not used to build generalized models.</p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, please contact us at: <a href="mailto:ladevzo-contact@googlegroups.com">ladevzo-contact@googlegroups.com</a></p>
    </div>
  );
}

export default PrivacyPolicyPage;